spring:
  data:
    mongodb:
      uri: ${DB_ENDPOINT:}

app:
  kafka:
    url: ${KAFKA_URL:localhost:9092}
    timeout: ${KAFKA_TIMEOUT:15000}
    clusterId: ${CLUSTER_ID:narcissus-core-dev-quang}

  channels:
    user: "user-service-channel"
    core: "core-service-channel"
    notification: "notification-service-channel"